# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20170117_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
